const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{BACKGROUD: 0},
	{Sólido: 0},
	{Grama: 0},
	{Fixar: 0},
	{animação: 0},
	{Teclado: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{jogador: 0},
	{cactos: 0},
	{marcador: 0},
	{ação: 0},
	{inimigo: 0},
	{Áudio: 0},
	{Sprite: 0},
	{JOIA: 0},
	{Âncora: 0},
	{Texto: 0},
	{borda: 0},
	{Sprite2: 0},
	{jogar: 0},
	{morto: 0},
	{pontos: 0}
];

self.InstanceType = {
	BACKGROUD: class extends self.ISpriteInstance {},
	Grama: class extends self.ISpriteInstance {},
	animação: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	jogador: class extends self.ISpriteInstance {},
	cactos: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	JOIA: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	borda: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	jogar: class extends self.ITextInstance {}
}